
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CheckLanguage.cmake:164 (message)"
      - "CMakeLists.txt:27 (check_language)"
    checks:
      - "Looking for a CUDA compiler"
    message: |
      Looking for a CUDA compiler failed with the following output:
      CMake Error at /opt/homebrew/share/cmake/Modules/Internal/CMakeCUDAFindToolkit.cmake:104 (message):
        Failed to find nvcc.
      
        Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
        variable.
      Call Stack (most recent call first):
        /opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:109 (cmake_cuda_find_toolkit)
        CMakeLists.txt:13 (project)
      
      
      -- Configuring incomplete, errors occurred!
      
...
