
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:13 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/mohammedakramlrhorfi/miniforge3/envs/oKoK/bin/"
      - "/Users/mohammedakramlrhorfi/miniforge3/condabin/"
      - "/opt/gcc-fsf-gnat/bin/"
      - "/Library/TeX/texbin/"
      - "/opt/homebrew/opt/python@3.14/bin/"
      - "/opt/homebrew/opt/openjdk@21/bin/"
      - "/Users/mohammedakramlrhorfi/.local/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/mohammedakramlrhorfi/.dotnet/tools/"
      - "/Users/mohammedakramlrhorfi/.cargo/bin/"
    searched_directories:
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/Users/mohammedakramlrhorfi/miniforge3/envs/oKoK/bin/uname"
      - "/Users/mohammedakramlrhorfi/miniforge3/condabin/uname"
      - "/opt/gcc-fsf-gnat/bin/uname"
      - "/Library/TeX/texbin/uname"
      - "/opt/homebrew/opt/python@3.14/bin/uname"
      - "/opt/homebrew/opt/openjdk@21/bin/uname"
      - "/Users/mohammedakramlrhorfi/.local/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/envs/oKoK/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/condabin"
        - "/opt/gcc-fsf-gnat/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/opt/python@3.14/bin"
        - "/opt/homebrew/opt/openjdk@21/bin"
        - "/Users/mohammedakramlrhorfi/.local/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Library/TeX/texbin"
        - "/usr/local/share/dotnet"
        - "/Users/mohammedakramlrhorfi/.dotnet/tools"
        - "/Users/mohammedakramlrhorfi/.cargo/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:13 (project)"
    message: |
      The system is: Darwin - 25.3.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompiler.cmake:54 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:39 (_cmake_find_compiler)"
      - "CMakeLists.txt:13 (project)"
    mode: "program"
    variable: "CMAKE_CUDA_COMPILER"
    description: "CUDA compiler"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "nvcc"
    candidate_directories:
      - "/opt/gcc-fsf-gnat/bin/"
    searched_directories:
      - "/opt/gcc-fsf-gnat/bin/nvcc"
    found: false
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/envs/oKoK/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/condabin"
        - "/opt/gcc-fsf-gnat/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/opt/python@3.14/bin"
        - "/opt/homebrew/opt/openjdk@21/bin"
        - "/Users/mohammedakramlrhorfi/.local/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Library/TeX/texbin"
        - "/usr/local/share/dotnet"
        - "/Users/mohammedakramlrhorfi/.dotnet/tools"
        - "/Users/mohammedakramlrhorfi/.cargo/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1303 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:99 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: [^
      ]+ Cuda compiler driver":
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1303 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:99 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CMakeCUDAFindToolkit.cmake:15 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:109 (cmake_cuda_find_toolkit)"
      - "CMakeLists.txt:13 (project)"
    mode: "program"
    variable: "_CUDA_NVCC_EXECUTABLE"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "nvcc"
      - "nvcc.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/envs/oKoK/bin"
        - "/Users/mohammedakramlrhorfi/miniforge3/condabin"
        - "/opt/gcc-fsf-gnat/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/opt/python@3.14/bin"
        - "/opt/homebrew/opt/openjdk@21/bin"
        - "/Users/mohammedakramlrhorfi/.local/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Library/TeX/texbin"
        - "/usr/local/share/dotnet"
        - "/Users/mohammedakramlrhorfi/.dotnet/tools"
        - "/Users/mohammedakramlrhorfi/.cargo/bin"
...
